layout-location: "DefaultLayout"                # The location of the layout file ImGui writes to
load-layout: true                               # Whether to load the layout file ImGui writes to
save-layout: true                               # Whether to automatically save to the layout file ImGui writes to
icon: "ude-welcome.png"                         # The location of the window icon image
width: 800                                      # Width of the window in pixels
height: 600                                     # Height of the window in pixels
fullscreen: false                               # Enable or disable fullscreen mode
window-name: Untitled Desktop Welcome           # The name of the window